'use client';

import { useMemo, useState } from 'react';
import { Boxes, Calculator, ChevronDown, CircleDollarSign, Clock3, Factory, FileText, Gauge, HandCoins, LayoutDashboard, Menu, PackageOpen, Plus, Search, Settings, ShoppingBag, TrendingUp, Users, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Progress } from '@/components/ui/progress';

const nav = [[LayoutDashboard, 'Visão geral'], [FileText, 'Orçamentos'], [ShoppingBag, 'Pedidos'], [Factory, 'Produção'], [Boxes, 'Estoque'], [Users, 'Clientes'], [CircleDollarSign, 'Financeiro'], [Settings, 'Configurações']] as const;
const orders = [
  { id: '#1048', client: 'Lumina Arquitetura', item: 'Maquete residencial', value: 'R$ 1.480,00', due: 'Hoje, 16:00', status: 'Em produção', tone: 'blue' },
  { id: '#1047', client: 'Studio Objeto', item: 'Kit 12 expositores', value: 'R$ 864,00', due: 'Amanhã', status: 'Aguardando', tone: 'amber' },
  { id: '#1046', client: 'Rafael Martins', item: 'Engrenagem técnica', value: 'R$ 295,00', due: '30 ago', status: 'Acabamento', tone: 'violet' },
  { id: '#1045', client: 'Clínica Orto+', item: 'Modelo anatômico', value: 'R$ 720,00', due: '02 set', status: 'Aprovado', tone: 'green' },
];
const jobs = [
  { machine: 'Bambu Lab X1C', job: 'Maquete • peças 8/14', time: '5h 20min restantes', progress: 64, color: '#2563eb' },
  { machine: 'Creality K1 Max', job: 'Engrenagem técnica', time: '1h 45min restantes', progress: 82, color: '#7c3aed' },
  { machine: 'Elegoo Saturn 3', job: 'Modelo anatômico', time: 'Preparando arquivo', progress: 18, color: '#0891b2' },
];

const money = (value: number) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);

export function DashboardApp() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [material, setMaterial] = useState(180);
  const [hours, setHours] = useState(9.5);
  const [margin, setMargin] = useState(35);
  const estimate = useMemo(() => {
    const materialCost = material * 0.095;
    const energy = hours * 0.86;
    const machine = hours * 3.4;
    const packaging = 8;
    const subtotal = materialCost + energy + machine + packaging;
    const fees = subtotal * 0.08;
    return { materialCost, energy, machine, fees, total: (subtotal + fees) / (1 - margin / 100) };
  }, [material, hours, margin]);

  const metrics: Array<[React.ElementType, string, string, string, string, string]> = [[HandCoins, 'Faturamento no mês', 'R$ 18.740', '+12,4%', 'vs. mês anterior', 'green'], [ShoppingBag, 'Pedidos ativos', '12', '4', 'entregas nesta semana', 'blue'], [Factory, 'Máquinas em uso', '3 de 5', '60%', 'da capacidade', 'orange'], [TrendingUp, 'Lucro estimado', 'R$ 6.920', '36,9%', 'margem média', 'violet']];

  return <div className="min-h-screen bg-[#f4f7fb] text-[#172033]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[238px] flex-col border-r border-white/8 bg-[#101a2d] text-white transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex h-[76px] items-center gap-2.5 border-b border-white/8 px-4"><img src="/imprimo3dlab-logo-white.png" alt="" className="h-11 w-12 shrink-0 object-contain"/><div className="min-w-0"><p className="truncate text-[16px] font-bold tracking-tight">Imprimo3DLab</p><p className="text-[10px] uppercase tracking-[.17em] text-slate-400">Gerenciamento</p></div><button className="ml-auto lg:hidden" aria-label="Fechar menu" onClick={() => setMobileOpen(false)}><X className="size-5" /></button></div>
      <nav className="flex-1 space-y-1 px-3 py-5"><p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">Operação</p>{nav.map(([Icon, label], index) => <button key={label} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${index === 0 ? 'bg-white/10 font-semibold text-white shadow-inner' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon className={`size-[18px] ${index === 0 ? 'text-[#ff8358]' : ''}`} />{label}{label === 'Produção' && <span className="ml-auto rounded-full bg-[#ff6b35] px-1.5 py-0.5 text-[10px] text-white">3</span>}</button>)}</nav>
      <div className="m-3 rounded-xl border border-white/8 bg-white/5 p-3.5"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#2d4162] text-xs font-bold">RS</div><div className="min-w-0"><p className="truncate text-sm font-medium">Renato Silva</p><p className="text-[11px] text-slate-400">Administrador</p></div><ChevronDown className="ml-auto size-4 text-slate-500" /></div></div>
    </aside>
    <main className="lg:pl-[238px]">
      <header className="sticky top-0 z-20 flex h-[76px] items-center border-b border-[#e4e9f1] bg-white/95 px-4 backdrop-blur sm:px-7"><button className="mr-3 lg:hidden" aria-label="Abrir menu" onClick={() => setMobileOpen(true)}><Menu /></button><div><h1 className="text-lg font-bold tracking-tight sm:text-xl">Visão geral</h1><p className="hidden text-xs text-slate-500 sm:block">Sexta-feira, 29 de agosto</p></div><div className="ml-auto hidden w-64 items-center gap-2 rounded-lg border border-[#dfe5ee] bg-[#f8fafc] px-3 md:flex"><Search className="size-4 text-slate-400" /><input className="h-9 w-full bg-transparent text-sm outline-none" placeholder="Buscar pedido ou cliente..." /></div><Button className="ml-3 h-10 rounded-lg bg-[#ff6b35] px-4 text-white shadow-sm hover:bg-[#e85c2b]"><Plus /> <span className="hidden sm:inline">Novo orçamento</span></Button></header>
      <div className="mx-auto max-w-[1540px] p-4 sm:p-7">
        <div className="mb-6 flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-sm text-slate-500">Bom dia, Renato.</p><h2 className="text-2xl font-bold tracking-[-.025em]">Sua produção está no ritmo certo.</h2></div><div className="flex items-center gap-2 text-xs text-slate-500"><span className="size-2 rounded-full bg-emerald-500" /> Atualizado agora</div></div>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([Icon, label, value, change, detail, color]) => <Card key={label} className="gap-3 border-0 bg-white py-4 shadow-[0_3px_16px_rgba(30,48,78,.06)] ring-1 ring-[#e6eaf0]"><CardHeader className="flex flex-row items-center justify-between px-4"><CardTitle className="text-xs font-medium text-slate-500">{label}</CardTitle><div className={`metric-icon metric-${color}`}><Icon className="size-[17px]" /></div></CardHeader><CardContent className="px-4"><p className="text-2xl font-bold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-slate-400"><span className={`font-semibold ${color === 'green' ? 'text-emerald-600' : 'text-slate-600'}`}>{change}</span> {detail}</p></CardContent></Card>)}</section>
        <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(330px,.75fr)]">
          <div className="space-y-5"><Card className="border-0 bg-white shadow-[0_3px_16px_rgba(30,48,78,.06)] ring-1 ring-[#e6eaf0]"><CardHeader className="flex flex-row items-center justify-between border-b border-[#edf0f4] pb-4"><div><CardTitle className="font-bold">Pedidos recentes</CardTitle><p className="mt-0.5 text-xs text-slate-500">Acompanhe prazos e andamento</p></div><Button variant="ghost" className="text-xs text-[#e65d2c]">Ver todos</Button></CardHeader><CardContent className="overflow-x-auto px-0"><table className="w-full min-w-[680px] text-left"><thead><tr className="border-b border-[#edf0f4] text-[10px] uppercase tracking-[.08em] text-slate-400"><th className="px-4 py-3 font-semibold">Pedido / cliente</th><th className="px-3 py-3 font-semibold">Trabalho</th><th className="px-3 py-3 font-semibold">Prazo</th><th className="px-3 py-3 font-semibold">Valor</th><th className="px-4 py-3 font-semibold">Status</th></tr></thead><tbody>{orders.map(order => <tr key={order.id} className="border-b border-[#f0f2f5] last:border-0 hover:bg-slate-50/70"><td className="px-4 py-3"><p className="text-xs font-bold">{order.id}</p><p className="text-[11px] text-slate-500">{order.client}</p></td><td className="px-3 py-3 text-xs font-medium">{order.item}</td><td className="px-3 py-3 text-xs text-slate-500">{order.due}</td><td className="px-3 py-3 text-xs font-semibold">{order.value}</td><td className="px-4 py-3"><Badge variant="secondary" className={`status-${order.tone}`}>{order.status}</Badge></td></tr>)}</tbody></table></CardContent></Card>
            <Card className="border-0 bg-white shadow-[0_3px_16px_rgba(30,48,78,.06)] ring-1 ring-[#e6eaf0]"><CardHeader className="flex flex-row items-center justify-between pb-2"><div><CardTitle className="font-bold">Fila de produção</CardTitle><p className="mt-0.5 text-xs text-slate-500">3 máquinas trabalhando agora</p></div><Gauge className="size-5 text-slate-400" /></CardHeader><CardContent className="grid gap-3 pt-1 md:grid-cols-3">{jobs.map(job => <div key={job.machine} className="rounded-xl border border-[#e8ecf2] p-3.5"><div className="flex items-center gap-2"><span className="relative flex size-2.5"><span className="absolute inline-flex size-full animate-ping rounded-full bg-emerald-400 opacity-60"/><span className="relative size-2.5 rounded-full bg-emerald-500"/></span><p className="text-xs font-bold">{job.machine}</p></div><p className="mt-3 text-[11px] font-medium text-slate-600">{job.job}</p><Progress value={job.progress} className="mt-2 [&_[data-slot=progress-indicator]]:bg-[var(--job-color)]" style={{'--job-color': job.color} as React.CSSProperties} /><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>{job.time}</span><b className="text-slate-600">{job.progress}%</b></div></div>)}</CardContent></Card></div>
          <Card className="h-fit border-0 bg-[#15233b] py-0 text-white shadow-[0_12px_30px_rgba(19,33,56,.18)] ring-0"><CardHeader className="rounded-t-xl border-b border-white/10 bg-[#1b2c49] py-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-lg bg-[#ff6b35]"><Calculator className="size-[18px]" /></div><div><CardTitle className="font-bold text-white">Orçamento rápido</CardTitle><p className="text-[11px] text-slate-400">Simule o preço de uma peça</p></div></div></CardHeader><CardContent className="space-y-4 px-4 py-4"><div className="grid grid-cols-2 gap-3"><label className="text-[11px] text-slate-300">Material (g)<Input type="number" value={material} onChange={e => setMaterial(Number(e.target.value))} className="mt-1 border-white/10 bg-white/8 text-white" /></label><label className="text-[11px] text-slate-300">Tempo (horas)<Input type="number" step="0.5" value={hours} onChange={e => setHours(Number(e.target.value))} className="mt-1 border-white/10 bg-white/8 text-white" /></label></div><label className="block text-[11px] text-slate-300">Margem de lucro <span className="float-right font-bold text-white">{margin}%</span><input aria-label="Margem de lucro" type="range" min="10" max="60" value={margin} onChange={e => setMargin(Number(e.target.value))} className="mt-2 w-full accent-[#ff6b35]" /></label><div className="space-y-2 rounded-xl bg-white/6 p-3 text-[11px]"><div className="flex justify-between text-slate-400"><span>Material</span><span className="text-slate-200">{money(estimate.materialCost)}</span></div><div className="flex justify-between text-slate-400"><span>Energia + máquina</span><span className="text-slate-200">{money(estimate.energy + estimate.machine)}</span></div><div className="flex justify-between text-slate-400"><span>Embalagem + taxas</span><span className="text-slate-200">{money(8 + estimate.fees)}</span></div><div className="mt-2 flex items-end justify-between border-t border-white/10 pt-3"><span className="text-xs font-medium text-white">Preço sugerido</span><span className="text-2xl font-bold text-[#ff8358]">{money(estimate.total)}</span></div></div><Button className="h-10 w-full bg-[#ff6b35] text-white hover:bg-[#e85c2b]"><FileText /> Criar orçamento completo</Button><p className="text-center text-[10px] text-slate-500">Cálculo inclui energia, depreciação, embalagem, taxas e margem.</p></CardContent></Card>
        </div>
        <section className="mt-5 grid gap-4 sm:grid-cols-3"><div className="flex items-center gap-3 rounded-xl border border-[#f1d9d0] bg-[#fff8f5] p-4"><PackageOpen className="size-5 text-[#e65d2c]"/><div><p className="text-xs font-bold">2 itens com estoque baixo</p><p className="text-[11px] text-slate-500">PLA Branco e Resina Cinza</p></div></div><div className="flex items-center gap-3 rounded-xl border border-blue-100 bg-blue-50/60 p-4"><Clock3 className="size-5 text-blue-600"/><div><p className="text-xs font-bold">18h de produção agendada</p><p className="text-[11px] text-slate-500">Capacidade livre amanhã: 11h</p></div></div><div className="flex items-center gap-3 rounded-xl border border-emerald-100 bg-emerald-50/60 p-4"><CircleDollarSign className="size-5 text-emerald-600"/><div><p className="text-xs font-bold">R$ 2.350 a receber</p><p className="text-[11px] text-slate-500">5 lançamentos em aberto</p></div></div></section>
      </div>
    </main>
    {mobileOpen && <button aria-label="Fechar navegação" className="fixed inset-0 z-30 bg-slate-950/35 lg:hidden" onClick={() => setMobileOpen(false)} />}
  </div>;
}
